services:
  db:
    image: postgres
    container_name: dbt_db
    hostname: dbt_db
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    env_file:
      - .env
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: dbt
    # docker exec -it dbt bash
    tty: true
    command:
      - /bin/bash
    entrypoint: []
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    user: "${UID}:${GID}"
    volumes:
      - type: bind
        source: ./proj
        target: /code/proj
      - /etc/passwd:/etc/passwd:ro
    working_dir: /code/proj
